from enum import Enum

class InvestigationType(str, Enum):
    INCIDENT_INVESTIGATION = "INCIDENT_INVESTIGATION"
    TRANSACTION_INVESTIGATION = "TRANSACTION_INVESTIGATION"
    STRATEGY_EXPLANATION = "STRATEGY_EXPLANATION"
    REVENUE_RISK_ANALYSIS = "REVENUE_RISK_ANALYSIS"
    WHAT_IF_EXPLANATION = "WHAT_IF_EXPLANATION"
    ROOT_CAUSE_EXPLANATION = "ROOT_CAUSE_EXPLANATION"
