from enum import Enum

class ScenarioType(str, Enum):
    CURRENT_CONDITIONS = "CURRENT_CONDITIONS"
    GATEWAY_DEGRADATION = "GATEWAY_DEGRADATION"
    GATEWAY_REROUTE = "GATEWAY_REROUTE"
    THRESHOLD_ADJUSTMENT = "THRESHOLD_ADJUSTMENT"
    CUSTOM_SCENARIO = "CUSTOM_SCENARIO"
